# Generated by Django 3.2 on 2021-04-07 09:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.URLField()),
                ('description', models.TextField()),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
