# Generated by Django 3.2 on 2021-04-08 04:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210407_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='landing-page', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.URLField(default='website-url', max_length=120),
        ),
    ]
