# Generated by Django 3.2 on 2021-04-08 05:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210408_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
